// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPerformanceSystem.Data;

#nullable disable

namespace StudentPerformanceSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250324232336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("StudentPerformanceSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2025, 3, 25, 2, 23, 35, 224, DateTimeKind.Local).AddTicks(1948),
                            ExamPoints = 80,
                            FirstName = "Иван",
                            Group = "ИТ-101",
                            LastName = "Иванов",
                            TaskPoints = 85,
                            TestPoints = 90
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2025, 3, 25, 2, 23, 35, 226, DateTimeKind.Local).AddTicks(4984),
                            ExamPoints = 70,
                            FirstName = "Петр",
                            Group = "ИТ-101",
                            LastName = "Петров",
                            TaskPoints = 75,
                            TestPoints = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
